
export const MOCK_REPORTS = [
    {
        id: 'rep_1',
        name: 'Monthly Performance Summary',
        type: 'Monthly',
        dateRange: 'Jan 1 - Jan 31, 2026',
        status: 'Finalized',
        clientVisible: true,
        lastUpdated: '2026-02-05',
        owner: 'Sarah Connor',
        subaccountId: 'sub_1',
    },
    {
        id: 'rep_2',
        name: 'Weekly SEO Insights',
        type: 'Weekly',
        dateRange: 'Feb 1 - Feb 7, 2026',
        status: 'Draft',
        clientVisible: false,
        lastUpdated: '2026-02-07',
        owner: 'John Doe',
        subaccountId: 'sub_2',
    },
    {
        id: 'rep_3',
        name: 'Q1 Strategy Review',
        type: 'Custom',
        dateRange: 'Jan 1 - Mar 31, 2026',
        status: 'Scheduled',
        clientVisible: false,
        lastUpdated: '2026-02-06',
        owner: 'Alice Smith',
        subaccountId: 'sub_1',
    },
    {
        id: 'rep_4',
        name: 'Daily Ad Spend Report',
        type: 'Daily',
        dateRange: 'Feb 6, 2026',
        status: 'Published',
        clientVisible: true,
        lastUpdated: '2026-02-07',
        owner: 'Bob Brown',
        subaccountId: 'sub_3',
    },
]
